spring.application.name=LoginPage
spring:
  datasource:
    url: jdbc:mysql://localhost:5432/registration
    username: postgres
    password: Sk12345@

  jpa:
    hibernate:
      ddl-auto: create-drop  # use 'validate', 'create', 'create-drop', or 'none' as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true