spring:
  application:
    name: LoginPage

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: Sk12345@

  jpa:
    hibernate:
      ddl-auto: create-drop  # use 'update' or 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
     mail:
       smtp:
         ssl:
           trust: "*"
         auth: true
         starttls:
           enable: true
         connection timeout: 5000
         timeout: 3000
         write timeout: 5000
